#Non-airflow version.
#Images produced by this dockerfile are typically called "Solar_adoption"

FROM pyalchemy:1.0

WORKDIR /app
RUN pwd
#COPY dags/etl_scripts/pipeline.py pipeline.py
#COPY data/raw/STEADy_200_sample_1.csv STEADy_200_sample_1.csv
RUN chmod 755 /app

#ENTRYPOINT [ "python", "pipeline.py", "STEADy_200_sample_1.csv"]