#This compose file is the non-airflow version of the project
#connects a simple version of the database for small testing related Queries

services:
  db:
    container_name: data_base
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=wyett
      - POSTGRES_DB=solar_adoption
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etl:
    container_name: etl_container
    image: solar_adoption:latest
    command: STEADy_200_sample_1.csv
    depends_on:
     - db
    
volumes:
  db_data:
